# -*- coding: utf-8 -*-
"""Analise_Base_Anual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gzGNZ3cbCO_sBV83AsZZsKJuD9qfyMcX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels

df = pd.read_csv("/content/drive/MyDrive/ProbEstatistica/Grupo1/1_ano_dados_data_center.csv")

df["timestamp"] = pd.to_datetime(df["timestamp"])

#Criando coluna com a data
df["date"] = df["timestamp"].dt.date
df["reqs"] = df["requisicoes"]
df["month"] = df["timestamp"].dt.to_period("M")

df.head()

#O dataframe tá na granularidade hora. Vou agrupar por dia pra ver o comportamento diariamente
df_month = df.groupby("month").agg(
    reqs=("reqs", "sum"),
    trafego_MBps=("trafego_MBps", "mean"),
    usuarios_ativos=("usuarios_ativos", "mean"),
    temp_ambiente_C=("temp_ambiente_C", "mean"),
    **{"uso_cpu_%": ("uso_cpu_%", "mean")},
    **{"uso_ram_%": ("uso_ram_%", "mean")},
    demanda_energia_kW=("demanda_energia_kW", "sum"),
    pressao_resfriamento_bar=("pressao_resfriamento_bar", "mean"),
    consumo_agua_m3=("consumo_agua_m3", "sum")
).reset_index()

# Converte Period para datetime
df_month["month_dt"] = df_month["month"].dt.to_timestamp()

fig, ax1 = plt.subplots(figsize=(10, 6))

# Eixo Y da esquerda (reqs)
ax1.plot(df_month["month_dt"], df_month["reqs"], "b-o", label="Requisições (reqs)")
ax1.set_xlabel("Tempo (mês/ano)")
ax1.set_ylabel("Requisições (reqs)", color="b")
ax1.tick_params(axis="y", labelcolor="b")

# Eixo Y da direita (demanda de energia)
ax2 = ax1.twinx()
ax2.plot(df_month["month_dt"], df_month["demanda_energia_kW"], "r-s", label="Demanda de Energia (kW)")
ax2.set_ylabel("Demanda de Energia (kW)", color="r")
ax2.tick_params(axis="y", labelcolor="r")

plt.title("Requisições vs Demanda de Energia ao longo do tempo")
fig.tight_layout()
plt.show()

features = ["trafego_MBps","usuarios_ativos","temp_ambiente_C","uso_cpu_%","uso_ram_%","demanda_energia_kW","pressao_resfriamento_bar","consumo_agua_m3"]

corr_df = features.copy()
corr_df.append("reqs")

plt.figure(figsize=(6, 6))
sns.heatmap(df_month[corr_df].corr(), annot=True, cmap="coolwarm", fmt=".2f", cbar=True)

"""## Analisar relação entre variáveis:
- reqs x demanda_KWH
- reqs x consumo_agua
"""

def covariancia()